# Automatic deployment using Ansible 

name: Continuous Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: dawidd6/action-ansible-playbook@v2
        env: 
          ANSIBLE_HOST_KEY_CHECKING: False
        with: 
          playbook: deploy.yml
          directory: ./dist/ansible/
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [development]
            ${{secrets.IP_1}}
            ${{secrets.IP_2}}
            ${{secrets.IP_3}}
          options: |
            --extra-vars ANSIBLE_HOST_KEY_CHECKING=FALSE
            --verbose
            
          
